# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: 
- none
#  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  kubernetesConnection: 'platform-demos-apis-ns'
  registryConnection: '42css-connection'
  platformUrl: 'https://demolabs.42crunch.cloud'
  azureResourceGroup: Demos
  namespace: axl
  API_UUID: 8b6c7fe2-2151-45ee-a448-0b5e9c505f76
  SCAN_API_UUID: e773f4f8-6282-491b-9b7a-227ce15a91b4
  targetDirectory: configs
  imageName: nginx-pixi
  tag: v0.1

  config_name: basicsetup
  #Testing only!
  PIXI_user: "user-inbound@acme.com"
  PIXI_pass: "hellopixi"

  #protectionsConnection: 'ProtectionsRepoConnection'

# resources:
#  repositories:
#    - repository: protections
#      type: github
#      endpoint: $(protectionsConnection)
#      name: 42c-presales/policies
  
steps:
# - checkout: self
# - checkout: protections
- task: NodeTool@0
  displayName: Use Node 12 or higher
  inputs:
    versionSpec: '=12.0.0'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10' 
    addToPath: true 
    #architecture: 'x64' # Options: x86, x64 (this argument applies only on Windows agents)

- script: python -m pip install requests --upgrade pip
  displayName: 'Install tools'

- task: APIContractSecurityAudit@3
  displayName: Auditing OAS Files
  inputs:
    apiToken: '$(42C_API_TOKEN)'
    minScore: '75'
    platformUrl: '$(platformUrl)'
    logLevel: DEBUG
    defaultCollectionName: 'Discovered APIs'

# - task: 42CrunchConformanceService@1
#   displayName: Launching Conformance Scan V1
#   inputs:
#     job_name: '$(Build.BuildId)-v1'
#     platform_hostname: 'demolabs.42crunch.cloud'
#     scan_manager_url: 'https://photo-demo.westeurope.cloudapp.azure.com/scand'
#     scan_image: '42crunch/scand-agent:v1.22.6'
#     api_id: '$(API_UUID)'
#     job_expiration_time: 3600
#   env:
#     SCAN_TOKEN: $(PIXI_SCAN_TOKEN)    


